/**
 * Error codes compartilhados
 */

export const ERROR_CODES = {
  // Auth errors
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Betfair API errors
  API_RATE_LIMIT: 'API_RATE_LIMIT',
  API_INVALID_REQUEST: 'API_INVALID_REQUEST',
  API_NOT_FOUND: 'API_NOT_FOUND',
  API_TIMEOUT: 'API_TIMEOUT',
  API_SERVER_ERROR: 'API_SERVER_ERROR',

  // Trading errors
  TRADE_INVALID_STAKE: 'TRADE_INVALID_STAKE',
  TRADE_INVALID_ODDS: 'TRADE_INVALID_ODDS',
  TRADE_INSUFFICIENT_FUNDS: 'TRADE_INSUFFICIENT_FUNDS',
  TRADE_MARKET_CLOSED: 'TRADE_MARKET_CLOSED',
  TRADE_REJECTED: 'TRADE_REJECTED',

  // Risk errors
  RISK_EXPOSURE_EXCEEDED: 'RISK_EXPOSURE_EXCEEDED',
  RISK_DAILY_LOSS_EXCEEDED: 'RISK_DAILY_LOSS_EXCEEDED',
  RISK_DRAWDOWN_EXCEEDED: 'RISK_DRAWDOWN_EXCEEDED',
  RISK_MAX_POSITIONS_EXCEEDED: 'RISK_MAX_POSITIONS_EXCEEDED',
  RISK_HALTED: 'RISK_HALTED',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Database errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONFLICT: 'DATABASE_CONFLICT',

  // Unknown
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
